"""add cover image fields

Revision ID: 9a8c1564ea3d
Revises: e3f7022ca94c
Create Date: 2026-05-08 11:40:15.732850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a8c1564ea3d'
down_revision = 'e3f7022ca94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_filename', sa.String(length=255), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('cover_image_filename')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('cover_image_filename')

    # ### end Alembic commands ###
