"""add tags and public discovery pages support

Revision ID: 9ebd2f7dfcf8
Revises: 98bf6f6b900a
Create Date: 2026-05-08 12:18:56.109690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebd2f7dfcf8'
down_revision = '98bf6f6b900a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=512), nullable=True))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('tags')

    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
